name: lark_auth_server
server_id: 1
log: "./configs/logger.yaml"
grpc_server:
  name: lark_auth_server
  server_id: 1
  port: 6600
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
    enabled: true
  jaeger:
    host_port: "lark-jaeger:6831"
    sampler_type: "const"
    param: 1
    log_spans: true
    buffer_flush_interval: 1
    max_packet_size: 0
    enabled: false
etcd:
  endpoints: ["lark-etcd-01:12379","lark-etcd-02:12381","lark-etcd-03:12383"]
  username:
  password:
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  max_open_conns: 20
  max_idle_conns: 10
  max_lifetime: 120000
  max_idle_time: 7200000
  charset: utf8
  sources:
    - {address: "lark-mysql-user-01:13306",username: root,password: lark2022,db: lark_user}
    - {address: "lark-mysql-user-02:13307",username: root,password: lark2022,db: lark_user}
  replicas:
    - {address: "lark-mysql-user-03:13308",username: root,password: lark2022,db: lark_user}
    - {address: "lark-mysql-user-04:13309",username: root,password: lark2022,db: lark_user}
redis:
  address: ["lark-redis-01:7001","lark-redis-02:7002","lark-redis-03:7003","lark-redis-04:7004"]
  db: 0
  password: lark2022
  prefix: "LK:"
chat_member_server:
  name: lark_chat_member_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
jaeger:
  host_port: "lark-jaeger:6831"
  sampler_type: "const"
  param: 1
  log_spans: true
  buffer_flush_interval: 1
  max_packet_size: 0
  enabled: false
github_oauth2:
  client_id: "Iv1.4a3ecfaf2c5e4f1a"
  client_secret: "05805d8d884ec2b2525b286e81f9ef4954e9622d"
  redirect_url: "http://localhost:8088/open/auth/github/callback"
google_oauth2:
  client_id: "913029687366-om9n4ca3427i8sjpf831dcfvs5itgtco.apps.googleusercontent.com"
  client_secret: "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"
  redirect_url: "http://localhost:8088/open/auth/google/callback"
  scopes: ["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email"]
  auth_url: "https://accounts.google.com/o/oauth2/auth"
  token_url: "https://accounts.google.com/o/oauth2/token"
